# Generated by Django 2.1.5 on 2019-04-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nascimento',
            field=models.DateField(default='2000-01-01', verbose_name='Data de Nascimento'),
        ),
    ]
