# Generated by Django 2.1.5 on 2019-02-05 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_remove_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N', models.FloatField()),
                ('P', models.FloatField()),
                ('K', models.FloatField()),
                ('S', models.FloatField()),
                ('Ca', models.FloatField()),
                ('Mg', models.FloatField()),
                ('Al', models.FloatField()),
                ('MO', models.FloatField()),
                ('Mn', models.FloatField()),
                ('Zn', models.FloatField()),
                ('Cu', models.FloatField()),
                ('Fe', models.FloatField()),
                ('B', models.FloatField()),
                ('SO4', models.FloatField()),
                ('pH', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Fazenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=2)),
                ('cidade', models.CharField(max_length=200)),
                ('tipo', models.IntegerField(default=0)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User')),
            ],
        ),
        migrations.CreateModel(
            name='Produtividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producao', models.FloatField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Safra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano1', models.CharField(max_length=4)),
                ('ano2', models.CharField(max_length=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User')),
            ],
        ),
        migrations.CreateModel(
            name='Talhao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tamanho', models.IntegerField(default=0)),
                ('tipo', models.CharField(default=1, max_length=1)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sinteagros.Fazenda')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User')),
            ],
            options={
                'verbose_name_plural': 'Talhoes',
            },
        ),
        migrations.AddField(
            model_name='produtividade',
            name='safra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sinteagros.Safra'),
        ),
        migrations.AddField(
            model_name='produtividade',
            name='talhao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sinteagros.Talhao'),
        ),
        migrations.AddField(
            model_name='produtividade',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User'),
        ),
        migrations.AddField(
            model_name='analise',
            name='safra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sinteagros.Safra'),
        ),
        migrations.AddField(
            model_name='analise',
            name='talhao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sinteagros.Talhao'),
        ),
        migrations.AddField(
            model_name='analise',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User'),
        ),
    ]
