# Generated by Django 2.1.5 on 2019-02-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinteagros', '0003_produtividade_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtividade',
            name='produto',
        ),
        migrations.AddField(
            model_name='talhao',
            name='produto',
            field=models.CharField(default='Soja', max_length=10),
        ),
    ]
