# Generated by Django 2.1.5 on 2019-02-18 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinteagros', '0004_auto_20190206_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analise',
            name='safra',
        ),
        migrations.RemoveField(
            model_name='analise',
            name='talhao',
        ),
        migrations.RemoveField(
            model_name='analise',
            name='user',
        ),
        migrations.DeleteModel(
            name='Analise',
        ),
    ]
