# Generated by Django 2.1.5 on 2019-02-18 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_username'),
        ('sinteagros', '0005_auto_20190218_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=40)),
                ('module', models.CharField(default=None, max_length=10)),
                ('id_task', models.IntegerField(default=0)),
                ('hour', models.TimeField()),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User')),
            ],
        ),
    ]
