# Generated by Django 2.1.5 on 2019-02-22 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinteagros', '0006_agenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='id_task',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='module',
        ),
    ]
