# Generated by Django 2.1.5 on 2019-02-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinteagros', '0007_auto_20190222_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='note',
            field=models.CharField(max_length=250),
        ),
    ]
