# Generated by Django 2.1.5 on 2019-04-10 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacao', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('history', models.CharField(max_length=30)),
                ('obs', models.CharField(max_length=30)),
                ('valor', models.FloatField(max_length=10)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Conta')),
            ],
            options={
                'verbose_name': 'Extrato Bancário',
                'verbose_name_plural': 'Extratos Bancários',
            },
        ),
    ]
