# Generated by Django 2.1.5 on 2019-04-22 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_extrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrato',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
