# Generated by Django 2.1.5 on 2019-05-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_auto_20190422_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrato',
            name='obs',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
