# Generated by Django 2.1.5 on 2019-07-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0007_saldo_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldo_inicial',
            name='ano',
            field=models.PositiveIntegerField(),
        ),
    ]
