# Generated by Django 2.1.5 on 2019-07-12 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190410_1517'),
        ('financeiro', '0008_auto_20190709_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='saldo_inicial',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.User'),
            preserve_default=False,
        ),
    ]
