# Generated by Django 2.1.5 on 2019-07-13 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0009_saldo_inicial_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saldo_inicial',
            options={'verbose_name': 'Saldo do Mes', 'verbose_name_plural': 'Saldos dos Meses'},
        ),
    ]
