# Generated by Django 2.1.5 on 2019-02-12 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('nome', models.CharField(max_length=255)),
                ('codigo_ibge', models.IntegerField(blank=True, null=True, verbose_name='Código IBGE')),
                ('gentilico', models.CharField(blank=True, max_length=255, null=True, verbose_name='Gentílico')),
                ('populacao', models.IntegerField(blank=True, null=True, verbose_name='População em 2010')),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Área da unidade territorial (km²)')),
                ('densidade_demografica', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Densidade demográfica (hab/km²)')),
                ('pib', models.IntegerField(blank=True, null=True, verbose_name='PIB')),
                ('lat', models.CharField(blank=True, max_length=255, null=True, verbose_name='Latitude')),
                ('lng', models.CharField(blank=True, max_length=255, null=True, verbose_name='Longitude')),
                ('capital', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ('uf', 'nome'),
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(max_length=2)),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ('nome',),
            },
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localidades.Estado'),
        ),
    ]
