# Generated by Django 2.1.5 on 2019-10-15 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_auto_20190410_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('cpf', models.CharField(max_length=14, primary_key=True, serialize=False, unique=True, verbose_name='CPF')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('contratacao', models.DateField(verbose_name='Data de Contratação')),
                ('area', models.CharField(choices=[('ADM', 'Administração'), ('PROD', 'Produção'), ('MAN', 'Manutenção')], max_length=50, verbose_name='Area de atuação')),
                ('cargo', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('pagamento', models.IntegerField(default=0, help_text='Dia combinado para pagamento de salário', verbose_name='Dia limite de pagamento')),
                ('atualizacao', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User')),
            ],
        ),
    ]
