# Generated by Django 2.1.5 on 2019-09-13 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_auto_20190410_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('cpf', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('contratacao', models.DateField()),
                ('cargo', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User')),
            ],
        ),
    ]
