# Generated by Django 2.1.5 on 2019-10-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='area',
            field=models.CharField(max_length=50, verbose_name='Area de atuação'),
        ),
    ]
